const styles = {
    container: { backgroundColor: "white", color: "black", fontFamily: "Arial, sans-serif", padding: "20px", minHeight: "100vh", position: "relative"},
    header: { display: "flex", alignItems: "center", marginBottom: "20px", border: "2px solid black", borderRadius: "10px", padding: "15px"},
    title: { fontSize: "32px", fontWeight: "bold", margin: 0, flex: 1, textAlign: "center"},
    filterSection: { display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", width: "100%", padding: "10px 0", marginBottom: "20px", gap: "10px"},
    filterLabel: { fontSize: "16px", fontWeight: "bold"},
    select: { backgroundColor: "white", color: "black", border: "2px solid black", borderRadius: "10px", padding: "8px 28px", fontSize: "14px", width: "250px"},
    button: { backgroundColor: "#4a7c59", color: "white", border: "2px solid black", borderRadius: "10px", padding: "10px 24px", cursor: "pointer", fontSize: "14px", width: "200px", textAlign: "center", flex: "0 0 auto"},
    resetButton: { backgroundColor: "#8b2e2e", color: "white", border: "2px solid black", borderRadius: "10px", padding: "10px 24px", cursor: "pointer", fontSize: "14px", width: "200px", textAlign: "center", flex: "0 0 auto"},
    metricsGrid: { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "15px", marginBottom: "20px"},
    metricCard: { border: "2px solid black", borderRadius: "10px", padding: "15px", textAlign: "center"},
    metricLabel: { fontSize: "12px", marginBottom: "8px", fontWeight: "bold"},
    metricValue: { fontSize: "20px", fontWeight: "bold"},
    chartsGrid: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "15px", marginBottom: "20px"},
    chartContainer: { border: "2px solid black", borderRadius: "10px", padding: "15px", maxHeight: "450px"},
    chartTitle: { fontSize: "16px", fontWeight: "bold", marginBottom: "15px", textAlign: "center"},
    lineChart: { width: "100%", height: "120px", position: "relative"},
    chartLine: { stroke: "black", strokeWidth: "2", fill: "none"},
    pieChart: { display: "flex", justifyContent: "center", alignItems: "center", height: "120px"},
    pieContainer: { position: "relative", width: "100px", height: "100px"},
    pieLegend: { marginTop: "10px", fontSize: "12px"},
    legendItem: { display: "flex", alignItems: "center", gap: "5px", marginBottom: "5px"},
    legendColor: { width: "12px", height: "12px", borderRadius: "50%"},
    table: { width: "100%", borderCollapse: "collapse"},
    tableHeader: { backgroundColor: "#f0f0f0", padding: "8px", border: "1px solid black", fontSize: "12px", fontWeight: "bold"},
    tableCell: { padding: "8px", border: "1px solid black", fontSize: "12px"},
    tablesGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "15px", marginBottom: "20px"},
    tableContainer: { border: "2px solid black", borderRadius: "10px", padding: "15px"},
    tableTitle: { fontSize: "16px", fontWeight: "bold", marginBottom: "10px", textAlign: "center"},
    exportButton: { backgroundColor: "black9", color: "white", border: "2px solid black", borderRadius: "10px", padding: "12px 24px", cursor: "pointer", fontSize: "16px", fontWeight: "bold", float: "right"},
};

export default styles;