# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0642b91d1c3d3b39d853b7fe3893c409"
name = "redemption-solutionsss"
handle = "redemption-solutionsss"
application_url = "https://program-cookie-pee-arbitrary.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_orders, write_orders, read_customers, read_inventory, write_inventory, read_assigned_fulfillment_orders, write_assigned_fulfillment_orders, read_merchant_managed_fulfillment_orders, write_merchant_managed_fulfillment_orders, read_third_party_fulfillment_orders, write_third_party_fulfillment_orders, read_discounts, write_discounts, read_gift_cards, write_gift_cards, read_inventory, write_inventory, "

[auth]
redirect_urls = [
  "https://morgan-fabric-immediately-racing.trycloudflare.com/auth/callback",
  "https://morgan-fabric-immediately-racing.trycloudflare.com/auth/shopify/callback",
  "https://morgan-fabric-immediately-racing.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
