# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0642b91d1c3d3b39d853b7fe3893c409"
name = "redemption-solutionsss"
handle = "redemption-solutionsss"
application_url = "https://techno-captured-sci-category.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_orders, write_orders, read_customers, read_inventory, write_inventory"

[auth]
redirect_urls = [
  "https://techno-captured-sci-category.trycloudflare.com/auth/callback",
  "https://techno-captured-sci-category.trycloudflare.com/auth/shopify/callback",
  "https://techno-captured-sci-category.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
