# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c2f415f66df6ec14c9b7ccef564c014c"
name = "redeem-gift"
handle = "redeem-gift"
application_url = "https://hostels-stones-ram-ruling.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_customers,read_discounts,read_gift_cards,read_inventory,read_merchant_managed_fulfillment_orders,read_orders,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_discounts,write_gift_cards,write_inventory,write_merchant_managed_fulfillment_orders,write_orders,write_products,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://hostels-stones-ram-ruling.trycloudflare.com/auth/callback",
  "https://hostels-stones-ram-ruling.trycloudflare.com/auth/shopify/callback",
  "https://hostels-stones-ram-ruling.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
